'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Dotacion
    Public Property serie As String
    Public Property folio As Integer
    Public Property contenidoDotacion As String
    Public Property fechaAlta As Date
    Public Property fechaModificacion As Date
    Public Property activo As Boolean

End Class
